apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: staging
spec:
  hard:
    pods: "6"
    requests.cpu: "3"
    requests.memory: 6Gi
    limits.cpu: "4"
    limits.memory: 8Gi