apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: main-app-secrets
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: main-app-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /staging/main-app
