apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: microservice-secrets
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: microservice-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /dev/microservice
